#!/bin/zsh

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}
user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}
success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}
fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


gemrc=~/.gemrc
if [ -f "$gemrc" ]; then
  info "backing up existing .gemrc"
  mv $gemrc $gemrc.bckp
  success "backed up .gemrc"
fi
ln -s `pwd`/lib/gemrc.symlink $gemrc
success "setup .gemrc"
echo ''


psqlrc=~/.psqlrc
if [ -f "$psqlrc" ]; then
  info "backing up existing .psqlrc"
  mv $psqlrc $psqlrc.bckp
  success "backed up .psqlrc"
fi
ln -s `pwd`/lib/psqlrc.symlink $psqlrc
success "setup .psqlrc"
echo ''


gitignore=~/.gitignore
if [ -f "$gitignore" ]; then
  info "backing up existing ~/.gitignore"
  mv $gitignore $gitignore.bckp
  success "backed up .gitignore"
fi
ln -s `pwd`/lib/git/gitignore.symlink $gitignore
success "setup .gitignore"
echo ''


gitconfig=~/.gitconfig
if [ -f "$gitconfig" ]; then
  info "backing up existing .gitconfig"
  mv $gitconfig $gitconfig.bckp
  success "backed up .gitconfig"
fi
vared -p 'git author name? ' -c git_authorname
vared -p 'git author email? ' -c git_authoremail
sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" `pwd`/lib/git/gitconfig.symlink.example > $gitconfig
success "setup gitconfig"
echo ''


#if [ $(uname) == 'Darwin' ]
#then
  #bash_profile=~/.bash_profile
  #if [ -f "$bash_profile" ]; then
    #info "backing up existing .bash_profile"
    #mv $bash_profile $bash_profile.bckp
    #success "backed up .bash_profile"
  #fi
  #ln -s `pwd`/bash_profile.symlink $bash_profile
  #. $bash_profile
  #success "setup and sourced .bash_profile"
#else
  #info "Not setting up .bash_profile because this is Linux (not Darwin)."
#fi
#echo ''


#bashrc=~/.bashrc
#if [ -f "$bashrc" ]; then
  #info "backing up existing .bashrc"
  #mv $bashrc $bashrc.bckp
  #success "backed up .bashrc"
#fi
#ln -s `pwd`/bashrc.symlink $bashrc
#. $bashrc
#success "setup and sourced .bashrc"
#echo ''

zshrc=~/.zshrc
if [ -f "$zshrc" ]; then
  info "backing up existing .zshrc"
  mv $zshrc $zshrc.bckp
  success "backed up .zshrc"
fi
ln -s `pwd`/zshrc.symlink $zshrc
. $zshrc
success "setup and sourced .zshrc"
echo ''



info "Setup the executables in ./bin/ to ~/bin/"
mkdir ~/bin
cp -r `pwd`/bin/* ~/bin/
success "executables copied to ~/bin/"


#if [ $(uname) == 'Darwin' ] # this works in bash
if [ $(uname) '==' 'Darwin' ] # this works in zsh
then
  info "Copy the launchd files to ~/Library/LaunchAgents dir"
fi
cp `pwd`/LaunchAgents/* ~/Library/LaunchAgents/
success "launchd plist files copied to ~/Library/LaunchAgents dir"
echo ''
